"use client";

import { useLanguage } from "@/context/LanguageContext";
import { Download } from "lucide-react";
import { motion } from "framer-motion";

export function FloatingCTA() {
  const { t } = useLanguage();
  
  const handleDownload = () => {
    // Generate a beautiful text-based dossier on the fly
    const dossierContent = `
=========================================
MAURIXR - STRATEGIC EXECUTIVE DOSSIER
=========================================
CONFIDENTIAL: FOR INTERNAL REVIEW ONLY
=========================================

1. EXECUTIVE SUMMARY
XR Technologies (VR/AR) present a massive leap in human capital development for the Islamic Republic of Mauritania, specifically targeting GTA, SNIM, and the Port of Nouadhibou.

IMPACT METRICS:
- Knowledge Retention: ~75%
- Workplace Safety Risk Reduction: -45%
- Training Infrastructure TCO Savings: ~50%

2. GLOBAL PARTNERS INCLUDED IN MATRIX:
- Pixaera (Oil & Gas - UK/USA)
- Luminous XR (Oil & Gas - UK)
- Immersive Technologies (Mining - Australia)
- VSTEP (Maritime - Netherlands)
- Next World XR (Construction - Australia)
- Avantis Education (TVET - UK)
- Avatar Medical (Healthcare - France)

Please refer to the interactive web portal for specific distribution opportunities, pricing architectures, and compliance standards for all 18 partners.

Generated by MauriXR Automated Systems.
=========================================
`;
    
    // Create blob and trigger download
    const blob = new Blob([dossierContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "MauriXR_Strategic_Dossier.txt";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 1, duration: 0.8 }}
      className="fixed bottom-8 right-8 z-[90]"
    >
      <button 
        onClick={handleDownload}
        className="group relative flex items-center space-x-3 bg-white/5 backdrop-blur-xl border border-white/20 px-6 py-4 rounded-full shadow-[0_0_30px_rgba(0,0,0,0.5)] hover:bg-white/10 transition-all overflow-hidden cursor-pointer"
      >
        {/* Animated Glow */}
        <div className="absolute inset-0 bg-gradient-to-r from-cyan-500/20 to-purple-500/20 opacity-0 group-hover:opacity-100 transition-opacity duration-500 rounded-full" />
        
        <div className="relative z-10 flex items-center justify-center w-8 h-8 rounded-full bg-gradient-to-r from-cyan-400 to-blue-500 text-white">
          <Download className="w-4 h-4 group-hover:-translate-y-1 group-hover:scale-110 transition-transform" />
        </div>
        <span className="relative z-10 text-sm font-bold tracking-widest uppercase text-white/90 group-hover:text-white">
          {t("Download Dossier", "Télécharger le Dossier")}
        </span>
      </button>
    </motion.div>
  );
}
